title=@$USER
separator="---"
info title-color=5
info underline=-

info0=OS
info0-value=$OS

info1=Host
info1-value=$HOSTNAME

info2=Kernel
info2-value=$KERNEL

info3=Uptime
info3-value=$UPTIME

info4=Packages
info4-value=$PACKAGES

info5=Shell
info5-value=$SHELL

info6=CPU
info6-value=$CPU

info7=Memory
info7-value=$MEMORY

logo=ascii
logo-width=40
logo-padding=5
logo-color=5
